/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVendedoresRouteImport } from './routes/app.vendedores'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppRateioRouteImport } from './routes/app.rateio'
import { Route as AppProdutosRouteImport } from './routes/app.produtos'
import { Route as AppPixRouteImport } from './routes/app.pix'
import { Route as AppPdvRouteImport } from './routes/app.pdv'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppInteligenciaRouteImport } from './routes/app.inteligencia'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppCategoriasRouteImport } from './routes/app.categorias'
import { Route as AppCaixaRouteImport } from './routes/app.caixa'
import { Route as ApiPublicWebhooksPixRouteImport } from './routes/api/public/webhooks/pix'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendedoresRoute = AppVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRateioRoute = AppRateioRouteImport.update({
  id: '/rateio',
  path: '/rateio',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPixRoute = AppPixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => AppRoute,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaRoute = AppInteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCaixaRoute = AppCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhooksPixRoute = ApiPublicWebhooksPixRouteImport.update({
  id: '/api/public/webhooks/pix',
  path: '/api/public/webhooks/pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/pix': typeof AppPixRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/rateio': typeof AppRateioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/app/': typeof AppIndexRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/pix': typeof AppPixRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/rateio': typeof AppRateioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/app': typeof AppIndexRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/pix': typeof AppPixRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/rateio': typeof AppRateioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/app/': typeof AppIndexRoute
  '/api/public/webhooks/pix': typeof ApiPublicWebhooksPixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/caixa'
    | '/app/categorias'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/inteligencia'
    | '/app/marketing'
    | '/app/pdv'
    | '/app/pix'
    | '/app/produtos'
    | '/app/rateio'
    | '/app/relatorios'
    | '/app/vendedores'
    | '/app/'
    | '/api/public/webhooks/pix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/caixa'
    | '/app/categorias'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/inteligencia'
    | '/app/marketing'
    | '/app/pdv'
    | '/app/pix'
    | '/app/produtos'
    | '/app/rateio'
    | '/app/relatorios'
    | '/app/vendedores'
    | '/app'
    | '/api/public/webhooks/pix'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/caixa'
    | '/app/categorias'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/inteligencia'
    | '/app/marketing'
    | '/app/pdv'
    | '/app/pix'
    | '/app/produtos'
    | '/app/rateio'
    | '/app/relatorios'
    | '/app/vendedores'
    | '/app/'
    | '/api/public/webhooks/pix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicWebhooksPixRoute: typeof ApiPublicWebhooksPixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendedores': {
      id: '/app/vendedores'
      path: '/vendedores'
      fullPath: '/app/vendedores'
      preLoaderRoute: typeof AppVendedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rateio': {
      id: '/app/rateio'
      path: '/rateio'
      fullPath: '/app/rateio'
      preLoaderRoute: typeof AppRateioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos': {
      id: '/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pix': {
      id: '/app/pix'
      path: '/pix'
      fullPath: '/app/pix'
      preLoaderRoute: typeof AppPixRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pdv': {
      id: '/app/pdv'
      path: '/pdv'
      fullPath: '/app/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inteligencia': {
      id: '/app/inteligencia'
      path: '/inteligencia'
      fullPath: '/app/inteligencia'
      preLoaderRoute: typeof AppInteligenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categorias': {
      id: '/app/categorias'
      path: '/categorias'
      fullPath: '/app/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caixa': {
      id: '/app/caixa'
      path: '/caixa'
      fullPath: '/app/caixa'
      preLoaderRoute: typeof AppCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhooks/pix': {
      id: '/api/public/webhooks/pix'
      path: '/api/public/webhooks/pix'
      fullPath: '/api/public/webhooks/pix'
      preLoaderRoute: typeof ApiPublicWebhooksPixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCaixaRoute: typeof AppCaixaRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppInteligenciaRoute: typeof AppInteligenciaRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppPdvRoute: typeof AppPdvRoute
  AppPixRoute: typeof AppPixRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRateioRoute: typeof AppRateioRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVendedoresRoute: typeof AppVendedoresRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaixaRoute: AppCaixaRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppInteligenciaRoute: AppInteligenciaRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppPdvRoute: AppPdvRoute,
  AppPixRoute: AppPixRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRateioRoute: AppRateioRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVendedoresRoute: AppVendedoresRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicWebhooksPixRoute: ApiPublicWebhooksPixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
